name: agenton


services:
  nginx:
    image: nginx:1.27
    ports:
      - "3030:3030"
      # - "[::]:3030:3030"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  frontend:
    image: frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    pull_policy: "build"
    expose:
      - "3000"

  backend:
    image: backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    pull_policy: "build"
    ports:
      - "8000:80"
