name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
      - run: |
          cd backend
          mkdir -p tests
          ls -la  # Show directory contents
          pip install -r requirements.txt
          python -m pytest -v tests/  # Run pytest with verbose output and explicit directory 